# This view is used to get the deployment in cluster1
apiVersion: view.open-cluster-management.io/v1beta1
kind: ManagedClusterView
metadata:
  name: getdeployment
  namespace: cluster1
spec:
  scope:
    resource: deployments
    name: foundation-agent
    namespace: open-cluster-management-agent
