kind: Service
apiVersion: v1
metadata:
  name: foundation-proxyserver
  namespace: open-cluster-management
spec:
  selector:
    app: foundation-proxyserver
  ports:
    - name: secure
      protocol: TCP
      port: 443
      targetPort: 6443
