# This action is used to delete nginx deployment in cluster1
apiVersion: action.open-cluster-management.io/v1beta1
kind: ManagedClusterAction
metadata:
  name: nginx-action-delete
  namespace: cluster1
spec:
  actionType: Delete
  kube:
    resource: deployment
    namespace: default
    name: nginx-deployment-action
